### ISSUE TITLE
ValueError: Could not flatten dictionary: key Tensor(...) is not unique.

### ISSUE THREAD

**Issue by TheJamesMachine** [dyelax/encore.ai#10]
I have tried training this same model a couple of times now (30k and 60k passes) and this problem persists. When I try to generate lyrics, it outputs a random word from the lyrics pile, then shows the Traceback below. 

It is Ubuntu 16.04. TensorFlow CPU (no GPU). I'm not sure why I installed things to the directories I did, but probably unrelated. I don't really know what I'm doing. 

Thanks for looking!

Traceback (most recent call last):
  File "runner.py", line 118, in <module>
    main()
  File "runner.py", line 114, in main
    LyricGenRunner(load_path, artist_name, test, prime_text)
  File "runner.py", line 52, in __init__
    self.test(prime_text)
  File "runner.py", line 81, in test
    sample = self.model.generate(prime=prime_text)
  File "/var/www/encore.ai/code/LSTMModel.py", line 181, in generate
    state = self.sess.run(self.final_state, feed_dict=feed_dict)
  File "/etc/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/etc/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1065, in _run
    feed_dict = nest.flatten_dict_items(feed_dict)
  File "/etc/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/util/nest.py", line 251, in flatten_dict_items
    % (new_i))
ValueError: Could not flatten dictionary: key Tensor("MultiRNNCellZeroState/BasicLSTMCellZeroState/zeros:0", shape=(1, 256), dtype=float32) is not unique.

**Comment by orvillem** [comment]
@TheJamesMachine I ran into the exact same issue using Tensorflow 1.5. Searching online I couldn't find a proper fix. There was a mention of using `state_is_tuple=False` in BasicLSTMCell but that didn't work for me. It is also being deprecated.

The only thing that worked that was not preferred was downgrading Tensorflow to 1.4. If you find a more suitable fix let us know.

**Comment by TheJamesMachine** [comment]
Thanks for the recommendation! I will try downgrading Tensorflow.

**Comment by xidiandb** [comment]
state_is_tuple=False was worker

**Comment by xidiandb** [comment]
state_is_tuple=False was worked in tf 1.5

**Comment by lettergram** [comment]
Is there a solution other than state_is_tuple=False?
